export const POPULATE_MENU = "POPULATE_MENU";
export const ADDTO_CART = "ADDTO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_SORTING = "UPDATE_SORTING";